FS-1427; Refactor sandbox to use anchors, and get it ready to refactor each service
metal-toolbox/sandbox pull request #73
Opened 2024-06-05 19:32 UTC by jakeschuurmans

Use anchors to re-use data in sandbox values.yaml

prepare services helmchart templates to be moved to their metal-toolbox/<service> github repos

2024-06-07 17:02 UTC, DoctorVin approved these changes

2024-06-07 17:02 UTC, DoctorVin commented on values.yaml
> +        oidc_scopes:    # to be filled by each service bellow
You might want to refer to the stuff you have below to save people making the same mistake I did. 😀

2024-06-07 17:14 UTC, jakeschuurmans commented on README.md
> +      --server ede81024-f62a-4288-8730-3fab8cceabcc\
will do

2024-06-11 23:38 UTC, DoctorVin requested changes
Sorry, I was a dope and commented in `internal monologue` instead of English.

2024-06-11 23:38 UTC, DoctorVin commented on templates/alloy-deployment.yaml
>              - name: ALLOY_FLEETDB_ENDPOINT
I wasn't clear. The token in `values.yaml` can have `fleetdb` in it, but the name of the environment variable must be `ALLOY_SERVERSERVICE_ENDPOINT`, cf. [this](https://github.com/metal-toolbox/alloy/blob/26374d074ae16435f7768d70743f505bca94da63/internal/app/config.go#L279)

2024-06-12 16:06 UTC, merged

2024-06-20 21:06 UTC, Alva8756 commented on templates/alloy-deployment.yaml
>              - name: ALLOY_FLEETDB_ENDPOINT
It looks the main is using `fleetdb`?
https://github.com/metal-toolbox/alloy/blob/main/internal/app/config.go#L278-L280

The link using `serverservice` is from the comit: 26374d074ae16435f7768d70743f505bca94da63

2024-06-20 21:40 UTC, DoctorVin commented on templates/alloy-deployment.yaml
>              - name: ALLOY_FLEETDB_ENDPOINT
My comment is from before Joel fixed Alloy 😁